name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install foundry
        run: curl -L https://foundry.paradigm.xyz | bash;

      - name: setup foundry
        run: /home/runner/.foundry/bin/foundryup

      - name: install deps
        run: yarn

      - name: build
        run: /home/runner/.foundry/bin/forge build

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test
